export const recipes = {
  "Pizza": [
    {
      "idMeal": "53014",
      "strMeal": "Pizza Express Margherita",
      "strMealAlternate": null,
      "strCategory": "Miscellaneous",
      "strArea": "Italian",
      "strInstructions": "1 Preheat the oven to 230\u00b0C.\r\n\r\n2 Add the sugar and crumble the fresh yeast into warm water.\r\n\r\n3 Allow the mixture to stand for 10 \u2013 15 minutes in a warm place (we find a windowsill on a sunny day works best) until froth develops on the surface.\r\n\r\n4 Sift the flour and salt into a large mixing bowl, make a well in the middle and pour in the yeast mixture and olive oil.\r\n\r\n5 Lightly flour your hands, and slowly mix the ingredients together until they bind.\r\n\r\n6 Generously dust your surface with flour.\r\n\r\n7 Throw down the dough and begin kneading for 10 minutes until smooth, silky and soft.\r\n\r\n8 Place in a lightly oiled, non-stick baking tray (we use a round one, but any shape will do!)\r\n\r\n9 Spread the passata on top making sure you go to the edge.\r\n\r\n10 Evenly place the mozzarella (or other cheese) on top, season with the oregano and black pepper, then drizzle with a little olive oil.\r\n\r\n11 Cook in the oven for 10 \u2013 12 minutes until the cheese slightly colours.\r\n\r\n12 When ready, place the basil leaf on top and tuck in!",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/x0lk931587671540.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=Mt5lgUZRoUg",
      "strIngredient1": "Water",
      "strIngredient2": "Sugar",
      "strIngredient3": "Yeast",
      "strIngredient4": "Plain Flour",
      "strIngredient5": "Salt",
      "strIngredient6": "Olive Oil",
      "strIngredient7": "Passata",
      "strIngredient8": "Mozzarella",
      "strIngredient9": "Oregano",
      "strIngredient10": "Basil",
      "strIngredient11": "Black Pepper",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "150ml",
      "strMeasure2": "1 tsp ",
      "strMeasure3": "15g",
      "strMeasure4": "225g",
      "strMeasure5": "1 1/2 tsp ",
      "strMeasure6": "Drizzle",
      "strMeasure7": "80g",
      "strMeasure8": "70g",
      "strMeasure9": "Peeled and Sliced",
      "strMeasure10": "Leaves",
      "strMeasure11": "Pinch",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://www.dailymail.co.uk/femail/food/article-8240361/Pizza-Express-release-secret-recipe-Margherita-Pizza-make-home.html",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    }
  ],
  "Sushi": [
    {
      "idMeal": "53065",
      "strMeal": "Sushi",
      "strMealAlternate": null,
      "strCategory": "Seafood",
      "strArea": "Japanese",
      "strInstructions": "STEP 1\r\nTO MAKE SUSHI ROLLS: Pat out some rice. Lay a nori sheet on the mat, shiny-side down. Dip your hands in the vinegared water, then pat handfuls of rice on top in a 1cm thick layer, leaving the furthest edge from you clear.\r\n\r\nSTEP 2\r\nSpread over some Japanese mayonnaise. Use a spoon to spread out a thin layer of mayonnaise down the middle of the rice.\r\n\r\nSTEP 3\r\nAdd the filling. Get your child to top the mayonnaise with a line of their favourite fillings \u2013 here we\u2019ve used tuna and cucumber.\r\n\r\nSTEP 4\r\nRoll it up. Lift the edge of the mat over the rice, applying a little pressure to keep everything in a tight roll.\r\n\r\nSTEP 5\r\nStick down the sides like a stamp. When you get to the edge without any rice, brush with a little water and continue to roll into a tight roll.\r\n\r\nSTEP 6\r\nWrap in cling film. Remove the mat and roll tightly in cling film before a grown-up cuts the sushi into thick slices, then unravel the cling film.\r\n\r\nSTEP 7\r\nTO MAKE PRESSED SUSHI: Layer over some smoked salmon. Line a loaf tin with cling film, then place a thin layer of smoked salmon inside on top of the cling film.\r\n\r\nSTEP 8\r\nCover with rice and press down. Press about 3cm of rice over the fish, fold the cling film over and press down as much as you can, using another tin if you have one.\r\n\r\nSTEP 9\r\nTip it out like a sandcastle. Turn block of sushi onto a chopping board. Get a grown-up to cut into fingers, then remove the cling film.\r\n\r\nSTEP 10\r\nTO MAKE SUSHI BALLS: Choose your topping. Get a small square of cling film and place a topping, like half a prawn or a small piece of smoked salmon, on it. Use damp hands to roll walnut-sized balls of rice and place on the topping.\r\n\r\nSTEP 11\r\nMake into tight balls. Bring the corners of the cling film together and tighten into balls by twisting it up, then unwrap and serve.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/g046bb1663960946.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=ub68OxEypaY",
      "strIngredient1": "Sushi Rice",
      "strIngredient2": "Rice wine",
      "strIngredient3": "Caster Sugar",
      "strIngredient4": "Mayonnaise",
      "strIngredient5": "Rice wine",
      "strIngredient6": "Soy Sauce",
      "strIngredient7": "Cucumber",
      "strIngredient8": "",
      "strIngredient9": "",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "300ml ",
      "strMeasure2": "100ml",
      "strMeasure3": "2 tbs",
      "strMeasure4": "3 tbs",
      "strMeasure5": "1 tbs",
      "strMeasure6": "1 tbs",
      "strMeasure7": "1",
      "strMeasure8": " ",
      "strMeasure9": " ",
      "strMeasure10": " ",
      "strMeasure11": " ",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://www.bbcgoodfood.com/recipes/simple-sushi",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    }
  ],
  "Pasta": [
    {
      "idMeal": "52777",
      "strMeal": "Mediterranean Pasta Salad",
      "strMealAlternate": null,
      "strCategory": "Seafood",
      "strArea": "Italian",
      "strInstructions": "Bring a large saucepan of salted water to the boil\r\nAdd the pasta, stir once and cook for about 10 minutes or as directed on the packet.\r\nMeanwhile, wash the tomatoes and cut into quarters. Slice the olives. Wash the basil.\r\nPut the tomatoes into a salad bowl and tear the basil leaves over them. Add a tablespoon of olive oil and mix.\r\nWhen the pasta is ready, drain into a colander and run cold water over it to cool it quickly.\r\nToss the pasta into the salad bowl with the tomatoes and basil.\r\nAdd the sliced olives, drained mozzarella balls, and chunks of tuna. Mix well and let the salad rest for at least half an hour to allow the flavours to mingle.\r\nSprinkle the pasta with a generous grind of black pepper and drizzle with the remaining olive oil just before serving.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/wvqpwt1468339226.jpg",
      "strTags": "Pasta,Baking",
      "strYoutube": "https://www.youtube.com/watch?v=e52IL8zYmaE",
      "strIngredient1": "mozzarella balls",
      "strIngredient2": "baby plum tomatoes",
      "strIngredient3": "fresh basil",
      "strIngredient4": "farfalle",
      "strIngredient5": "extra virgin olive oil",
      "strIngredient6": "Green Olives",
      "strIngredient7": "tuna",
      "strIngredient8": "salt",
      "strIngredient9": "pepper",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": null,
      "strIngredient17": null,
      "strIngredient18": null,
      "strIngredient19": null,
      "strIngredient20": null,
      "strMeasure1": "200 g",
      "strMeasure2": "250 g",
      "strMeasure3": "1  bunch",
      "strMeasure4": "350 g",
      "strMeasure5": "3  tablespoons",
      "strMeasure6": "40 g",
      "strMeasure7": "200 g",
      "strMeasure8": "to taste",
      "strMeasure9": "to taste",
      "strMeasure10": "",
      "strMeasure11": "",
      "strMeasure12": "",
      "strMeasure13": "",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": null,
      "strMeasure17": null,
      "strMeasure18": null,
      "strMeasure19": null,
      "strMeasure20": null,
      "strSource": "https://thelemonsqueezy.com/recipe/mediterranean-pasta-salad/",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    }
  ],
  "Tacos": [
    {
      "idMeal": "52819",
      "strMeal": "Cajun spiced fish tacos",
      "strMealAlternate": null,
      "strCategory": "Seafood",
      "strArea": "Mexican",
      "strInstructions": "Cooking in a cajun spice and cayenne pepper marinade makes this fish super succulent and flavoursome. Top with a zesty dressing and serve in a tortilla for a quick, fuss-free main that's delightfully summery.\r\n\r\nOn a large plate, mix the cajun spice and cayenne pepper with a little seasoning and use to coat the fish all over.\r\n\r\nHeat a little oil in a frying pan, add in the fish and cook over a medium heat until golden. Reduce the heat and continue frying until the fish is cooked through, about 10 minutes. Cook in batches if you don\u2019t have enough room in the pan.\r\n\r\nMeanwhile, prepare the dressing by combining all the ingredients with a little seasoning.\r\nSoften the tortillas by heating in the microwave for 5-10 seconds. Pile high with the avocado, lettuce and spring onion, add a spoonful of salsa, top with large flakes of fish and drizzle over the dressing.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/uvuyxu1503067369.jpg",
      "strTags": "Spicy,Fish",
      "strYoutube": "https://www.youtube.com/watch?v=N4EdUt0Ou48",
      "strIngredient1": "cajun",
      "strIngredient2": "cayenne pepper",
      "strIngredient3": "white fish",
      "strIngredient4": "vegetable oil",
      "strIngredient5": "flour tortilla",
      "strIngredient6": "avocado",
      "strIngredient7": "little gem lettuce",
      "strIngredient8": "Spring Onions",
      "strIngredient9": "salsa",
      "strIngredient10": "sour cream",
      "strIngredient11": "lemon",
      "strIngredient12": "garlic",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "2 tbsp",
      "strMeasure2": "1 tsp",
      "strMeasure3": "4 fillets",
      "strMeasure4": "1 tsp",
      "strMeasure5": "8",
      "strMeasure6": "1 sliced",
      "strMeasure7": "2 shredded",
      "strMeasure8": "4 shredded",
      "strMeasure9": "1 x 300ml",
      "strMeasure10": "1 pot",
      "strMeasure11": "1",
      "strMeasure12": "1 clove finely chopped",
      "strMeasure13": "",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": "",
      "strMeasure17": "",
      "strMeasure18": "",
      "strMeasure19": "",
      "strMeasure20": "",
      "strSource": "https://realfood.tesco.com/recipes/cajun-spiced-fish-tacos.html",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52830",
      "strMeal": "Crock Pot Chicken Baked Tacos",
      "strMealAlternate": null,
      "strCategory": "Chicken",
      "strArea": "Mexican",
      "strInstructions": "Put the uncooked chicken breasts in the crock pot. Pour the full bottle of salad dressing over the chicken. Sprinkle the rest of the ingredients over the top and mix them in a bit with a spoon.\r\nCover your crock pot with the lid and cook on high for 4 hours.\r\nRemove all the chicken breasts from the crock pot and let cool.\r\nShred the chicken breasts and move to a glass bowl.\r\nPour most of the liquid over the shredded chicken.\r\nFOR THE TACOS:\r\nMake the guacamole sauce by mixing the avocado and green salsa together. Pour the guacamole mixture through a strainer until smooth and transfer to a squeeze bottle. Cut the tip off the lid of the squeeze bottle to make the opening more wide if needed.\r\nMake the sour cream sauce by mixing the sour cream and milk together until you get a more liquid sour cream sauce. Transfer to a squeeze bottle.\r\nIn a 9x 13 glass baking dish, fill all 12+ tacos with a layer of refried beans, cooked chicken and shredded cheese.\r\nBake at 450 for 10-15 minutes just until the cheese is melted and bubbling.\r\nOut of the oven top all the tacos with the sliced grape tomaotes, jalapeno and cilantro.\r\nFinish with a drizzle of guacamole and sour cream.\r\nEnjoy!",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/ypxvwv1505333929.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=oqL0mLDBzS4",
      "strIngredient1": "Chicken Breasts",
      "strIngredient2": "Vinaigrette Dressing",
      "strIngredient3": "Cumin",
      "strIngredient4": "Smoked Paprika",
      "strIngredient5": "Garlic",
      "strIngredient6": "Refried Beans",
      "strIngredient7": "Hard Taco Shells",
      "strIngredient8": "Shredded Mexican Cheese",
      "strIngredient9": "Grape Tomatoes",
      "strIngredient10": "Jalapeno",
      "strIngredient11": "Avocado",
      "strIngredient12": "Green Salsa",
      "strIngredient13": "Sour Cream",
      "strIngredient14": "Milk",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "4 - 6",
      "strMeasure2": "1 bottle",
      "strMeasure3": "1\u00bd tablespoon",
      "strMeasure4": "1 tablespoon",
      "strMeasure5": "1 teaspoon",
      "strMeasure6": "1 can",
      "strMeasure7": "12",
      "strMeasure8": "2 cups",
      "strMeasure9": "Halved",
      "strMeasure10": "Sliced and Seeded",
      "strMeasure11": "Peeled and Sliced",
      "strMeasure12": "2 tablespoons",
      "strMeasure13": "3 tablespoons",
      "strMeasure14": "1 tablespoon",
      "strMeasure15": "",
      "strMeasure16": "",
      "strMeasure17": "",
      "strMeasure18": "",
      "strMeasure19": "",
      "strMeasure20": "",
      "strSource": "http://www.nobiggie.net/crock-pot-chicken-baked-tacos/",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    }
  ],
  "Chicken soup": [
    {
      "idMeal": "53020",
      "strMeal": "Rosol (Polish Chicken Soup)",
      "strMealAlternate": null,
      "strCategory": "Chicken",
      "strArea": "Polish",
      "strInstructions": "Add chicken to a large Dutch oven or stock pot \r\nCover with water\r\nBring to a boil and simmer for 2 to 2 1/2 hours, skimming any impurities off the top to insure a clear broth\r\nIf your pot is big enough, add the vegetables and spices for the last hour of the cooking time\r\nMy Dutch oven wasn\u2019t big enough to hold everything, just the chicken and other bones filled the pot, so I cooked the meat/bones for the full cooking time, then removed them, and cooked the vegetables and spices separately\r\nStrain everything out of the broth\r\nBone the chicken, pulling the meat into large chunks\r\nSlice the carrots\r\nReturn the chicken and carrots to the broth\r\nCook noodles according to package instructions if you\u2019re using them\r\nAdd noodles to bowl and then top with hot soup",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/lx1kkj1593349302.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=AU60fxyxXGw",
      "strIngredient1": "Chicken Legs",
      "strIngredient2": "Onions",
      "strIngredient3": "Carrots",
      "strIngredient4": "Leek",
      "strIngredient5": "Celery",
      "strIngredient6": "Cabbage",
      "strIngredient7": "Cloves",
      "strIngredient8": "Allspice",
      "strIngredient9": "Bay Leaf",
      "strIngredient10": "Parsley",
      "strIngredient11": "Dill",
      "strIngredient12": "Pepper",
      "strIngredient13": "Salt",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "4 Chopped",
      "strMeasure2": "2 large",
      "strMeasure3": "5 chopped",
      "strMeasure4": "1 chopped",
      "strMeasure5": "1 small",
      "strMeasure6": "1/4 ",
      "strMeasure7": "1 whole",
      "strMeasure8": "1tsp",
      "strMeasure9": "2",
      "strMeasure10": "4 sprigs",
      "strMeasure11": "4 sprigs",
      "strMeasure12": "1 tsp ",
      "strMeasure13": "1 tbs",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://polishhousewife.com/rosol-polish-chicken-soup/",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    }
  ],
  "Mac and Cheese": [
    {
      "idMeal": "52818",
      "strMeal": "Chicken Fajita Mac and Cheese",
      "strMealAlternate": null,
      "strCategory": "Chicken",
      "strArea": "American",
      "strInstructions": "Fry your onion, peppers and garlic in olive oil until nicely translucent. Make a well in your veg and add your chicken. Add your seasoning and salt. Allow to colour slightly.\r\nAdd your cream, stock and macaroni.\r\nCook on low for 20 minutes. Add your cheeses, stir to combine.\r\nTop with roasted peppers and parsley.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/qrqywr1503066605.jpg",
      "strTags": "Pasta,Cheasy,Meat",
      "strYoutube": "https://www.youtube.com/watch?v=bwTSmLTZKNg",
      "strIngredient1": "macaroni",
      "strIngredient2": "chicken stock",
      "strIngredient3": "heavy cream",
      "strIngredient4": "fajita seasoning",
      "strIngredient5": "salt",
      "strIngredient6": "chicken breast",
      "strIngredient7": "olive oil",
      "strIngredient8": "onion",
      "strIngredient9": "red pepper",
      "strIngredient10": "garlic",
      "strIngredient11": "cheddar cheese",
      "strIngredient12": "parsley",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "500g",
      "strMeasure2": "2 cups",
      "strMeasure3": "1/2 cup",
      "strMeasure4": "1 packet",
      "strMeasure5": "1 tsp",
      "strMeasure6": "3 diced",
      "strMeasure7": "2 tbsp",
      "strMeasure8": "1 small finely diced",
      "strMeasure9": "2 finely diced",
      "strMeasure10": "2 cloves minced",
      "strMeasure11": "1 cup",
      "strMeasure12": "garnish chopped",
      "strMeasure13": "",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": "",
      "strMeasure17": "",
      "strMeasure18": "",
      "strMeasure19": "",
      "strMeasure20": "",
      "strSource": "http://twistedfood.co.uk/chicken-fajita-mac-n-cheese/",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52829",
      "strMeal": "Grilled Mac and Cheese Sandwich",
      "strMealAlternate": null,
      "strCategory": "Pasta",
      "strArea": "American",
      "strInstructions": "Make the mac and cheese\r\n\r\n1. Bring a medium saucepan of generously salted water (you want it to taste like seawater) to a boil. Add the pasta and cook, stirring occasionally, until al dente, 8 to 10 minutes, or according to the package directions. The pasta should be tender but still chewy.\r\n2. While the pasta is cooking, in a small bowl, whisk together the flour, mustard powder, garlic powder, salt, black pepper, and cayenne pepper.\r\n3. Drain the pasta in a colander. Place the empty pasta pan (no need to wash it) over low heat and add the butter. When the butter has melted, whisk in the flour mixture and continue to cook, whisking frequently, until the mixture is beginning to brown and has a pleasant, nutty aroma, about 1 minute. Watch carefully so it does not scorch on the bottom of the pan.\r\n4. Slowly whisk the milk and cream into the flour mixture until everything is really well combined. Cook, whisking constantly, until the sauce is heated through and just begins to thicken, about 2 minutes. Remove from the heat. Gradually add the cheese while stirring constantly with a wooden spoon or silicone spatula and keep stirring until the cheese has melted into the sauce. Then stir in the drained cooked pasta.\r\n5. Line a 9-by-13-inch (23-by-33-centimeter) rimmed baking sheet with parchment paper or aluminum foil. Coat the paper or foil with nonstick cooking spray or slick it with butter. Pour the warm mac and cheese onto the prepared baking sheet and spread it evenly with a spatula. Coat another piece of parchment paper with cooking spray or butter and place it, oiled or buttered side down, directly on the surface of the mac and cheese. Refrigerate until cool and firm, about 1 hour.\r\n\r\nMake the grilled cheese\r\n6. Heat a large cast-iron or nonstick skillet over medium-low heat.\r\n7. In a small bowl, stir together the 4 tablespoons (55 grams) butter and garlic powder until well blended.\r\n8. Remove the mac and cheese from the refrigerator and peel off the top layer of parchment paper. Carefully cut into 8 equal pieces. Each piece will make 1 grilled mac and cheese sandwich. (You can stash each individual portion in a double layer of resealable plastic bags and refrigerate for up to 3 days or freeze it for up to 1 month.)\r\n9. Spread 3/4 teaspoon garlic butter on one side of each bread slice. Place half of the slices, buttered-side down, on a clean cutting board. Top each with one slice of Cheddar, then 1 piece of the mac and cheese. (Transfer from the baking sheet by scooting your hand or a spatula under each piece of mac and cheese and then flipping it over onto a sandwich.) Place 1 slice of Jack on top of each. Finish with the remaining bread slices, buttered-side up.\r\n10. Using a wide spatula, place as many sandwiches in the pan as will fit without crowding it. Cover and cook until the bottoms are nicely browned, about 4 minutes. Turn and cook until the second sides are browned, the cheese is melted, and the mac and cheese is heated through, about 4 minutes more.\r\n11. Repeat with the remaining ingredients. Cut the sandwiches in half, if desired, and serve.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/xutquv1505330523.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=PYq31xLj-DY",
      "strIngredient1": "Macaroni",
      "strIngredient2": "Plain Flour",
      "strIngredient3": "Mustard Powder",
      "strIngredient4": "Garlic powder",
      "strIngredient5": "Kosher salt",
      "strIngredient6": "Black pepper",
      "strIngredient7": "Cayenne pepper",
      "strIngredient8": "Butter",
      "strIngredient9": "Whole Milk",
      "strIngredient10": "Heavy Cream",
      "strIngredient11": "Monterey Jack Cheese",
      "strIngredient12": "Butter",
      "strIngredient13": "garlic powder",
      "strIngredient14": "Bread",
      "strIngredient15": "Cheddar Cheese",
      "strIngredient16": "Colby Jack Cheese",
      "strIngredient17": "Butter",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "8 ounces (230 grams)",
      "strMeasure2": "1/3 cup",
      "strMeasure3": "3/4 teaspoon",
      "strMeasure4": "1/2 teaspoon",
      "strMeasure5": "1/2 teaspoon",
      "strMeasure6": "1/2 teaspoon",
      "strMeasure7": "1/8 teaspoon",
      "strMeasure8": "6 tablespoons (85 grams)",
      "strMeasure9": "1 1/2 cups (360 milliliters)",
      "strMeasure10": "1 cup (240 milliliters)",
      "strMeasure11": "1 pound (455 grams) ",
      "strMeasure12": "4 tablespoons (55 grams)",
      "strMeasure13": "1 teaspoon",
      "strMeasure14": "16 slices square",
      "strMeasure15": "8 slices mild",
      "strMeasure16": "8 slices",
      "strMeasure17": "4 tablespoons (55 grams)",
      "strMeasure18": "",
      "strMeasure19": "",
      "strMeasure20": "",
      "strSource": "https://leitesculinaria.com/103647/recipes-grilled-mac-and-cheese-sandwich.html",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    }
  ],
  "Beef": [
    {
      "idMeal": "53071",
      "strMeal": "Beef Asado",
      "strMealAlternate": null,
      "strCategory": "Beef",
      "strArea": "Filipino",
      "strInstructions": "0.\tCombine beef, crushed peppercorn, soy sauce, vinegar, dried bay leaves, lemon, and tomato sauce. Mix well. Marinate beef for at least 30 minutes.\r\n1.\tPut the marinated beef in a cooking pot along with remaining marinade. Add water. Let boil.\r\n2.\tAdd Knorr Beef Cube. Stir. Cover the pot and cook for 40 minutes in low heat.\r\n3.\tTurn the beef over. Add tomato paste. Continue cooking until beef tenderizes. Set aside.\r\n4.\tHeat oil in a pan. Fry the potato until it browns. Turn over and continue frying the opposite side. Remove from the pan and place on a clean plate. Do the same with the carrots.\r\n5.\tSave 3 tablespoons of cooking oil from the pan where the potato was fried. Saute onion and garlic until onion softens.\r\n6.\tPour-in the sauce from the beef stew. Let boil. Add the beef. Cook for 2 minutes.\r\n7.\tAdd butter and let it melt. Continue cooking until the sauce reduces to half.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/pkopc31683207947.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=lNlK8DVhXXA",
      "strIngredient1": "Beef",
      "strIngredient2": "Beef Stock Concentrate",
      "strIngredient3": "Tomato Puree",
      "strIngredient4": "Water",
      "strIngredient5": "Soy Sauce",
      "strIngredient6": "White Wine Vinegar",
      "strIngredient7": "Pepper",
      "strIngredient8": "Bay Leaf",
      "strIngredient9": "Lemon",
      "strIngredient10": "Tomato Sauce",
      "strIngredient11": "Butter",
      "strIngredient12": "Olive Oil",
      "strIngredient13": "Onion",
      "strIngredient14": "Garlic",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "1.5kg",
      "strMeasure2": "1",
      "strMeasure3": "8 ounces",
      "strMeasure4": "3 cups ",
      "strMeasure5": "6 tablespoons",
      "strMeasure6": "1 tbs",
      "strMeasure7": "2 tbs",
      "strMeasure8": "4",
      "strMeasure9": "1/2 ",
      "strMeasure10": "2 tbs",
      "strMeasure11": "3 tbs",
      "strMeasure12": "1/2 cup ",
      "strMeasure13": "1 chopped",
      "strMeasure14": "4 cloves",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://panlasangpinoy.com/beef-asado/",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52952",
      "strMeal": "Beef Lo Mein",
      "strMealAlternate": null,
      "strCategory": "Beef",
      "strArea": "Chinese",
      "strInstructions": "STEP 1 - MARINATING THE BEEF\r\nIn a bowl, add the beef, salt, 1 pinch white pepper, 1 Teaspoon sesame seed oil, 1/2 egg, corn starch,1 Tablespoon of oil and mix together.\r\nSTEP 2 - BOILING THE THE NOODLES\r\nIn a 6 qt pot add your noodles to boiling water until the noodles are submerged and boil on high heat for 10 seconds. After your noodles is done boiling strain and cool with cold water.\r\nSTEP 3 - STIR FRY\r\nAdd 2 Tablespoons of oil, beef and cook on high heat untill beef is medium cooked.\r\nSet the cooked beef aside\r\nIn a wok add 2 Tablespoon of oil, onions, minced garlic, minced ginger, bean sprouts, mushrooms, peapods and 1.5 cups of water or until the vegetables are submerged in water.\r\nAdd the noodles to wok\r\nTo make the sauce, add oyster sauce, 1 pinch white pepper, 1 teaspoon sesame seed oil, sugar, and 1 Teaspoon of soy sauce.\r\nNext add the beef to wok and stir-fry",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/1529444830.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=ZT9LSsNXXe0",
      "strIngredient1": "Beef",
      "strIngredient2": "Salt",
      "strIngredient3": "Pepper",
      "strIngredient4": "Sesame Seed Oil",
      "strIngredient5": "Egg",
      "strIngredient6": "Starch",
      "strIngredient7": "Oil",
      "strIngredient8": "Noodles",
      "strIngredient9": "Onion",
      "strIngredient10": "Minced Garlic",
      "strIngredient11": "Ginger",
      "strIngredient12": "Bean Sprouts",
      "strIngredient13": "Mushrooms",
      "strIngredient14": "Water",
      "strIngredient15": "Oyster Sauce",
      "strIngredient16": "Sugar",
      "strIngredient17": "Soy Sauce",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "1/2 lb",
      "strMeasure2": "pinch",
      "strMeasure3": "pinch",
      "strMeasure4": "2 tsp",
      "strMeasure5": "1/2 ",
      "strMeasure6": "3 tbs",
      "strMeasure7": "5 tbs",
      "strMeasure8": "1/4 lb",
      "strMeasure9": "1/2 cup ",
      "strMeasure10": "1 tsp ",
      "strMeasure11": "1 tsp ",
      "strMeasure12": "1 cup ",
      "strMeasure13": "1 cup ",
      "strMeasure14": "1 cup ",
      "strMeasure15": "1 tbs",
      "strMeasure16": "1 tsp ",
      "strMeasure17": "1 tsp ",
      "strMeasure18": "",
      "strMeasure19": "",
      "strMeasure20": "",
      "strSource": "https://sueandgambo.com/pages/beef-lo-mein",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "53053",
      "strMeal": "Beef Rendang",
      "strMealAlternate": null,
      "strCategory": "Beef",
      "strArea": "Malaysian",
      "strInstructions": "Chop the spice paste ingredients and then blend it in a food processor until fine.\r\nHeat the oil in a stew pot, add the spice paste, cinnamon, cloves, star anise, and cardamom and stir-fry until aromatic. Add the beef and the pounded lemongrass and stir for 1 minute. Add the coconut milk, tamarind juice, water, and simmer on medium heat, stirring frequently until the meat is almost cooked. Add the kaffir lime leaves, kerisik (toasted coconut), sugar or palm sugar, stirring to blend well with the meat.\r\nLower the heat to low, cover the lid, and simmer for 1 to 1 1/2 hours or until the meat is really tender and the gravy has dried up. Add more salt and sugar to taste. Serve immediately with steamed rice and save some for overnight.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/bc8v651619789840.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=Ot-dmfBaZrA",
      "strIngredient1": "Beef",
      "strIngredient2": "Vegetable Oil",
      "strIngredient3": "Cinnamon Stick",
      "strIngredient4": "Cloves",
      "strIngredient5": "Star Anise",
      "strIngredient6": "Cardamom",
      "strIngredient7": "Coconut Cream",
      "strIngredient8": "Water",
      "strIngredient9": "Tamarind Paste",
      "strIngredient10": "Lime",
      "strIngredient11": "Sugar",
      "strIngredient12": "Challots",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "1lb",
      "strMeasure2": "5 tbs",
      "strMeasure3": "1",
      "strMeasure4": "3",
      "strMeasure5": "3",
      "strMeasure6": "3",
      "strMeasure7": "1 cup ",
      "strMeasure8": "1 cup ",
      "strMeasure9": "2 tbs",
      "strMeasure10": "6",
      "strMeasure11": "1 tbs",
      "strMeasure12": "5",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://rasamalaysia.com/beef-rendang-recipe-rendang-daging/",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "53068",
      "strMeal": "Beef Mechado",
      "strMealAlternate": null,
      "strCategory": "Beef",
      "strArea": "Filipino",
      "strInstructions": "0.\tMake the beef tenderloin marinade by combining soy sauce, vinegar, ginger, garlic, sesame oil, olive oil, sugar, salt, and ground black pepper in a large bowl. Mix well.\r\n1.\tAdd the cubed beef tenderloin to the bowl with the beef tenderloin marinade. Gently toss to coat the beef. Let it stay for 1 hour.\r\n2.\tUsing a metal or bamboo skewer, assemble the beef kebob by skewering the vegetables and marinated beef tenderloin.\r\n3.\tHeat-up the grill and start grilling the beef kebobs for 3 minutes per side. This will give you a medium beef that is juicy and tender on the inside. Add more time if you want your beef well done, but it will be less tender.\r\n4.\tTransfer to a serving plate. Serve with Saffron rice.\r\n5.\tShare and enjoy!\r\n",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/cgl60b1683206581.jpg",
      "strTags": "Stew,Warming",
      "strYoutube": "https://www.youtube.com/watch?v=jxW3Lj8VjyE",
      "strIngredient1": "Garlic",
      "strIngredient2": "Onion",
      "strIngredient3": "Beef",
      "strIngredient4": "Tomato Puree",
      "strIngredient5": "Water",
      "strIngredient6": "Olive Oil",
      "strIngredient7": "Lemon",
      "strIngredient8": "Potatoes",
      "strIngredient9": "Soy Sauce",
      "strIngredient10": "Black Pepper",
      "strIngredient11": "Bay Leaves",
      "strIngredient12": "Salt",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "3 cloves",
      "strMeasure2": "1 sliced",
      "strMeasure3": "2 Lbs",
      "strMeasure4": "8 ounces",
      "strMeasure5": "1 cup ",
      "strMeasure6": "3 tbs",
      "strMeasure7": "1 Slice",
      "strMeasure8": "1 large",
      "strMeasure9": "1/4 cup",
      "strMeasure10": "1/2 tsp",
      "strMeasure11": "2",
      "strMeasure12": "To taste",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://panlasangpinoy.com/filipino-pinoy-food-tomato-sauce-beef-mechado-recipe/",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52950",
      "strMeal": "Szechuan Beef",
      "strMealAlternate": null,
      "strCategory": "Beef",
      "strArea": "Chinese",
      "strInstructions": "STEP 1 - MARINATING THE BEEF\r\nIn a bowl, add the beef, salt, sesame seed oil, white pepper, egg white, 2 Tablespoon of corn starch and 1 Tablespoon of oil.\r\nSTEP 2 - STIR FRY\r\nFirst Cook the beef by adding 2 Tablespoon of oil until the beef is golden brown.\r\nSet the beef aside\r\nIn a wok add 1 Tablespoon of oil, minced ginger, minced garlic and stir-fry for few seconds.\r\nNext add all of the vegetables and then add sherry cooking wine and 1 cup of water.\r\nTo make the sauce add oyster sauce, hot pepper sauce, and sugar.\r\nadd the cooked beef and 1 spoon of soy sauce\r\nTo thicken the sauce, whisk together 1 Tablespoon of cornstarch and 2 Tablespoon of water in a bowl and slowly add to your stir-fry until it's the right thickness.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/1529443236.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=SQGZqZYz7Ms",
      "strIngredient1": "Beef",
      "strIngredient2": "Salt",
      "strIngredient3": "Sesame Seed Oil",
      "strIngredient4": "Pepper",
      "strIngredient5": "Egg White",
      "strIngredient6": "Starch",
      "strIngredient7": "Oil",
      "strIngredient8": "Ginger",
      "strIngredient9": "Garlic",
      "strIngredient10": "Onion",
      "strIngredient11": "Carrots",
      "strIngredient12": "Green Pepper",
      "strIngredient13": "Celery",
      "strIngredient14": "Mushrooms",
      "strIngredient15": "Cooking wine",
      "strIngredient16": "Water",
      "strIngredient17": "Oyster Sauce",
      "strIngredient18": "Hotsauce",
      "strIngredient19": "Sugar",
      "strIngredient20": "Soy Sauce",
      "strMeasure1": "1/2 lb",
      "strMeasure2": "1/2 tsp",
      "strMeasure3": "1 tsp ",
      "strMeasure4": "1 pinch",
      "strMeasure5": "1",
      "strMeasure6": "3 tbs",
      "strMeasure7": "4 tbs",
      "strMeasure8": "1 tsp ",
      "strMeasure9": "1 tsp ",
      "strMeasure10": "3/4 cup ",
      "strMeasure11": "1/2 cup ",
      "strMeasure12": "3/4 cup ",
      "strMeasure13": "1 cup ",
      "strMeasure14": "1 cup ",
      "strMeasure15": "1 tbs",
      "strMeasure16": "1 cup ",
      "strMeasure17": "1 tbs",
      "strMeasure18": "1/2 tsp",
      "strMeasure19": "1 tsp ",
      "strMeasure20": "1 tbs",
      "strSource": "https://sueandgambo.com/pages/szechuan-beef",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "53070",
      "strMeal": "Beef Caldereta",
      "strMealAlternate": null,
      "strCategory": "Beef",
      "strArea": "Filipino",
      "strInstructions": "0.\tHeat oil in a cooking pot. Saute onion and garlic until onion softens\r\n1.\tAdd beef. Saute until the outer part turns light brown.\r\n2.\tAdd soy sauce. Pour tomato sauce and water. Let boil.\r\n3.\tAdd Knorr Beef Cube. Cover the pressure cooker. Cook for 30 minutes.\r\n4.\tPan-fry carrot and potato until it browns. Set aside.\r\n5.\tAdd chili pepper, liver spread and peanut butter. Stir.\r\n6.\tAdd bell peppers, fried potato and carrot. Cover the pot. Continue cooking for 5 to 7 minutes.\r\n7.\tSeason with salt and ground black pepper. Serve.\r\n",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/41cxjh1683207682.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=yI7hTz0ft5k",
      "strIngredient1": "Beef",
      "strIngredient2": "Beef Stock",
      "strIngredient3": "Soy Sauce",
      "strIngredient4": "Water",
      "strIngredient5": "Green Pepper",
      "strIngredient6": "Red Pepper",
      "strIngredient7": "Potatoes",
      "strIngredient8": "Carrots",
      "strIngredient9": "Tomato Puree",
      "strIngredient10": "Peanut Butter",
      "strIngredient11": "Chilli Powder",
      "strIngredient12": "Onion",
      "strIngredient13": "Garlic",
      "strIngredient14": "Olive Oil",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "2kg cut cubes",
      "strMeasure2": "1",
      "strMeasure3": "1 tbs",
      "strMeasure4": "2 cups ",
      "strMeasure5": "1 sliced",
      "strMeasure6": "1 sliced",
      "strMeasure7": "1 sliced",
      "strMeasure8": "1 sliced",
      "strMeasure9": "8 ounces",
      "strMeasure10": "3  tablespoons",
      "strMeasure11": "5",
      "strMeasure12": "1 chopped",
      "strMeasure13": "5 cloves",
      "strMeasure14": "3 tbs",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://www.kawalingpinoy.com/beef-caldereta/",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52803",
      "strMeal": "Beef Wellington",
      "strMealAlternate": null,
      "strCategory": "Beef",
      "strArea": "British",
      "strInstructions": "Put the mushrooms into a food processor with some seasoning and pulse to a rough paste. Scrape the paste into a pan and cook over a high heat for about 10 mins, tossing frequently, to cook out the moisture from the mushrooms. Spread out on a plate to cool.\r\nHeat in a frying pan and add a little olive oil. Season the beef and sear in the hot pan for 30 secs only on each side. (You don't want to cook it at this stage, just colour it). Remove the beef from the pan and leave to cool, then brush all over with the mustard.\r\nLay a sheet of cling film on a work surface and arrange the Parma ham slices on it, in slightly overlapping rows. With a palette knife, spread the mushroom paste over the ham, then place the seared beef fillet in the middle. Keeping a tight hold of the cling film from the edge, neatly roll the Parma ham and mushrooms around the beef to form a tight barrel shape. Twist the ends of the cling film to secure. Chill for 15-20 mins to allow the beef to set and keep its shape.\r\nRoll out the puff pastry on a floured surface to a large rectangle, the thickness of a \u00a31 coin. Remove the cling film from the beef, then lay in the centre. Brush the surrounding pastry with egg yolk. Fold the ends over, the wrap the pastry around the beef, cutting off any excess. Turn over, so the seam is underneath, and place on a baking sheet. Brush over all the pastry with egg and chill for about 15 mins to let the pastry rest.\r\nHeat the oven to 200C, 400F, gas 6.\r\nLightly score the pastry at 1cm intervals and glaze again with beaten egg yolk. Bake for 20 minutes, then lower the oven setting to 180C, 350F, gas 4 and cook for another 15 mins. Allow to rest for 10-15 mins before slicing and serving with the side dishes of your choice. The beef should still be pink in the centre when you serve it.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/vvpprx1487325699.jpg",
      "strTags": "Meat,Stew",
      "strYoutube": "https://www.youtube.com/watch?v=FS8u1RBdf6I",
      "strIngredient1": "mushrooms",
      "strIngredient2": "English Mustard",
      "strIngredient3": "Olive Oil",
      "strIngredient4": "Beef Fillet",
      "strIngredient5": "Parma ham",
      "strIngredient6": "Puff Pastry",
      "strIngredient7": "Flour",
      "strIngredient8": "Egg Yolks",
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strIngredient16": null,
      "strIngredient17": null,
      "strIngredient18": null,
      "strIngredient19": null,
      "strIngredient20": null,
      "strMeasure1": "400g",
      "strMeasure2": "1-2tbsp",
      "strMeasure3": "Dash",
      "strMeasure4": "750g piece",
      "strMeasure5": "6-8 slices",
      "strMeasure6": "500g",
      "strMeasure7": "Dusting",
      "strMeasure8": "2 Beaten ",
      "strMeasure9": "",
      "strMeasure10": "",
      "strMeasure11": "",
      "strMeasure12": "",
      "strMeasure13": "",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": "",
      "strMeasure17": "",
      "strMeasure18": "",
      "strMeasure19": "",
      "strMeasure20": "",
      "strSource": "http://www.goodtoknow.co.uk/recipes/164868/Gordon-Ramsay-s-beef-Wellington",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52834",
      "strMeal": "Beef stroganoff",
      "strMealAlternate": null,
      "strCategory": "Beef",
      "strArea": "Russian",
      "strInstructions": "Heat the olive oil in a non-stick frying pan then add the sliced onion and cook on a medium heat until completely softened, so around 15 mins, adding a little splash of water if they start to stick at all. Crush in the garlic and cook for a 2-3 mins further, then add the butter. Once the butter is foaming a little, add the mushrooms and cook for around 5 mins until completely softened. Season everything well, then tip onto a plate.\r\nTip the flour into a bowl with a big pinch of salt and pepper, then toss the steak in the seasoned flour. Add the steak pieces to the pan, splashing in a little oil if the pan looks particularly dry, and fry for 3-4 mins, until well coloured. Tip the onions and mushrooms back into the pan. Whisk the cr\u00e8me fra\u00eeche, mustard and beef stock together, then pour into the pan. Cook over a medium heat for around 5 mins. Scatter with parsley, then serve with pappardelle or rice.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/svprys1511176755.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=PQHgQX1Ss74",
      "strIngredient1": "Olive Oil",
      "strIngredient2": "Onions",
      "strIngredient3": "Garlic",
      "strIngredient4": "Butter",
      "strIngredient5": "Mushrooms",
      "strIngredient6": "Beef Fillet",
      "strIngredient7": "Plain Flour",
      "strIngredient8": "Creme Fraiche",
      "strIngredient9": "English Mustard",
      "strIngredient10": "Beef Stock",
      "strIngredient11": "Parsley",
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strIngredient16": null,
      "strIngredient17": null,
      "strIngredient18": null,
      "strIngredient19": null,
      "strIngredient20": null,
      "strMeasure1": "1 tbls",
      "strMeasure2": "1",
      "strMeasure3": "1 clove",
      "strMeasure4": "1 tbsp",
      "strMeasure5": "250g",
      "strMeasure6": "500g",
      "strMeasure7": "1tbsp",
      "strMeasure8": "150g",
      "strMeasure9": "1 tbsp",
      "strMeasure10": "100ml",
      "strMeasure11": "Topping",
      "strMeasure12": "",
      "strMeasure13": "",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": "",
      "strMeasure17": "",
      "strMeasure18": "",
      "strMeasure19": "",
      "strMeasure20": "",
      "strSource": "https://www.bbcgoodfood.com/recipes/beef-stroganoff",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52876",
      "strMeal": "Minced Beef Pie",
      "strMealAlternate": null,
      "strCategory": "Beef",
      "strArea": "British",
      "strInstructions": "Preheat the oven to 200C/400F/Gas 6.\r\nHeat the oil in a deep frying pan and fry the beef mince for 4-5 minutes, breaking it up with a wooden spoon as it browns.\r\nAdd the onion and cook for 2-3 minutes, then stir in the tomato pur\u00e9e and cook for 2-3 more minutes. Stir in the flour and cook for a further minute, then add the chopped mushrooms, the stout or beef stock and a couple of dashes of Worcestershire sauce. Bring to the boil, then reduce the heat, cover the pan with a lid and leave to simmer for 20 minutes. Set aside and leave to cool, then turn the meat mixture into a one litre pie dish.\r\nRoll out the pastry on a floured work surface until it is slightly larger than the pie dish. Gently drape the pastry over the dish, pressing firmly onto the edges. Trim, then shape the edges into a fluted shape.\r\nCut some leaf shapes out of the pastry trimmings and decorate the top of the pie, sticking them to the pastry with the beaten egg yolk.\r\nMake three or four slits in the pastry to allow the steam to escape, then brush the pie with the rest of the beaten egg yolk and bake in the oven for 20-25 minutes, or until golden-brown.\r\nTo serve, slice into wedges.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/xwutvy1511555540.jpg",
      "strTags": "Pie,Meat",
      "strYoutube": "https://www.youtube.com/watch?v=QY47h-uqq5g",
      "strIngredient1": "Vegetable Oil",
      "strIngredient2": "Minced Beef",
      "strIngredient3": "Onion",
      "strIngredient4": "Tomato Puree",
      "strIngredient5": "Plain Flour",
      "strIngredient6": "Mushrooms",
      "strIngredient7": "Beef Stock",
      "strIngredient8": "Worcestershire Sauce",
      "strIngredient9": "Shortcrust Pastry",
      "strIngredient10": "Egg Yolks",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "2 tbs",
      "strMeasure2": "500g",
      "strMeasure3": "1 chopped",
      "strMeasure4": "1 tbls",
      "strMeasure5": "1 \u00bd tbsp",
      "strMeasure6": "75g",
      "strMeasure7": "250ml",
      "strMeasure8": "Dash",
      "strMeasure9": "400g",
      "strMeasure10": "1",
      "strMeasure11": "",
      "strMeasure12": "",
      "strMeasure13": "",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": "",
      "strMeasure17": "",
      "strMeasure18": "",
      "strMeasure19": "",
      "strMeasure20": "",
      "strSource": "https://www.bbc.co.uk/food/recipes/mincedbeefpie_89198",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52904",
      "strMeal": "Beef Bourguignon",
      "strMealAlternate": null,
      "strCategory": "Beef",
      "strArea": "French",
      "strInstructions": "Heat a large casserole pan and add 1 tbsp goose fat. Season the beef and fry until golden brown, about 3-5 mins, then turn over and fry the other side until the meat is browned all over, adding more fat if necessary. Do this in 2-3 batches, transferring the meat to a colander set over a bowl when browned.\r\nIn the same pan, fry the bacon, shallots or pearl onions, mushrooms, garlic and bouquet garni until lightly browned. Mix in the tomato pur\u00e9e and cook for a few mins, stirring into the mixture. This enriches the bourguignon and makes a great base for the stew. Then return the beef and any drained juices to the pan and stir through.\r\nPour over the wine and about 100ml water so the meat bobs up from the liquid, but isn\u2019t completely covered. Bring to the boil and use a spoon to scrape the caramelised cooking juices from the bottom of the pan \u2013 this will give the stew more flavour.\r\nHeat oven to 150C/fan 130C/gas 2. Make a cartouche: tear off a square of foil slightly larger than the casserole, arrange it in the pan so it covers the top of the stew and trim away any excess foil. Then cook for 3 hrs. If the sauce looks watery, remove the beef and veg with a slotted spoon, and set aside. Cook the sauce over a high heat for a few mins until the sauce has thickened a little, then return the beef and vegetables to the pan.\r\nTo make the celeriac mash, peel the celeriac and cut into cubes. Heat the olive oil in a large frying pan. Tip in the celeriac and fry for 5 mins until it turns golden. Season well with salt and pepper. Stir in the rosemary, thyme, bay and cardamom pods, then pour over 200ml water, enough to nearly cover the celeriac. Turn the heat to low, partially cover the pan and leave to simmer for 25-30 mins.\r\nAfter 25-30 mins, the celeriac should be soft and most of the water will have evaporated. Drain away any remaining water, then remove the herb sprigs, bay and cardamom pods. Lightly crush with a potato masher, then finish with a glug of olive oil and season to taste. Spoon the beef bourguignon into serving bowls and place a large spoonful of the celeriac mash on top. Garnish with one of the bay leaves, if you like.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/vtqxtu1511784197.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=SQnr4Z-7rok",
      "strIngredient1": "Goose Fat",
      "strIngredient2": "Beef Shin",
      "strIngredient3": "Bacon",
      "strIngredient4": "Challots",
      "strIngredient5": "Chestnut Mushroom",
      "strIngredient6": "Garlic Clove",
      "strIngredient7": "Bouquet Garni",
      "strIngredient8": "Tomato Puree",
      "strIngredient9": "Red Wine",
      "strIngredient10": "Celeriac",
      "strIngredient11": "Olive Oil",
      "strIngredient12": "Thyme",
      "strIngredient13": "Rosemary",
      "strIngredient14": "Bay Leaf",
      "strIngredient15": "Cardamom",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "3 tsp",
      "strMeasure2": "600g",
      "strMeasure3": "100g ",
      "strMeasure4": "350g",
      "strMeasure5": "250g",
      "strMeasure6": "2 sliced",
      "strMeasure7": "1",
      "strMeasure8": "1 tbs",
      "strMeasure9": "750 ml ",
      "strMeasure10": "600g",
      "strMeasure11": "2 tbs",
      "strMeasure12": "sprigs of fresh",
      "strMeasure13": "sprigs of fresh",
      "strMeasure14": "2",
      "strMeasure15": "4",
      "strMeasure16": "",
      "strMeasure17": "",
      "strMeasure18": "",
      "strMeasure19": "",
      "strMeasure20": "",
      "strSource": "https://www.bbcgoodfood.com/recipes/5032/beef-bourguignon",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    }
  ],
  "Eggs": [
    {
      "idMeal": "52962",
      "strMeal": "Salmon Eggs Eggs Benedict",
      "strMealAlternate": null,
      "strCategory": "Breakfast",
      "strArea": "American",
      "strInstructions": "First make the Hollandaise sauce. Put the lemon juice and vinegar in a small bowl, add the egg yolks and whisk with a balloon whisk until light and frothy. Place the bowl over a pan of simmering water and whisk until mixture thickens. Gradually add the butter, whisking constantly until thick \u2013 if it looks like it might be splitting, then whisk off the heat for a few mins. Season and keep warm.\r\n\r\nTo poach the eggs, bring a large pan of water to the boil and add the vinegar. Lower the heat so that the water is simmering gently. Stir the water so you have a slight whirlpool, then slide in the eggs one by one. Cook each for about 4 mins, then remove with a slotted spoon.\r\n\r\nLightly toast and butter the muffins, then put a couple of slices of salmon on each half. Top each with an egg, spoon over some Hollandaise and garnish with chopped chives.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/1550440197.jpg",
      "strTags": "Bun,Brunch",
      "strYoutube": "https://www.youtube.com/watch?v=Woiiet4vQ58",
      "strIngredient1": "Eggs",
      "strIngredient2": "White Wine Vinegar",
      "strIngredient3": "English Muffins",
      "strIngredient4": "Butter",
      "strIngredient5": "Smoked Salmon",
      "strIngredient6": "Lemon Juice",
      "strIngredient7": "White Wine Vinegar",
      "strIngredient8": "Egg",
      "strIngredient9": "Unsalted Butter",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "4",
      "strMeasure2": "2 tbs",
      "strMeasure3": "2",
      "strMeasure4": "To serve",
      "strMeasure5": "8 slices",
      "strMeasure6": "2 tsp",
      "strMeasure7": "2 tsp",
      "strMeasure8": "3 Yolkes",
      "strMeasure9": "125g",
      "strMeasure10": " ",
      "strMeasure11": " ",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://www.bbcgoodfood.com/recipes/73606/eggs-benedict-with-smoked-salmon-and-chives",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    }
  ],
  "Sweet Potatoes": [
    {
      "idMeal": "52994",
      "strMeal": "Skillet Apple Pork Chops with Roasted Sweet Potatoes & Zucchini",
      "strMealAlternate": null,
      "strCategory": "Pork",
      "strArea": "American",
      "strInstructions": "\r\nServes 2\r\n\r\n\r\n1. \r\n\r\nAdjust racks to top and middle positions and preheat oven to 450 degrees. Wash and dry all produce. Dice sweet potatoes into 1/2-inch pieces. Toss on a baking sheet with a drizzle of oil, salt, and pepper. Roast on top rack for 12 minutes (we'll roast the zucchini then). \r\n\r\n\r\n2. \r\n\r\nMeanwhile, halve and core apple; thinly slice into half-moons. Peel and finely chop garlic. Quarter lemon. Trim and halve zucchini lengthwise; cut crosswise into 1/2-inch-thick half-moons. Toss on a second baking sheet with a drizzle of oil and a pinch of salt and pepper. Set aside. \r\n\r\n\r\n3. \r\n\r\nPat pork dry with paper towels and season all over with salt and pepper. Heat a drizzle of oil in a large pan over medium-high heat. Add pork and cook until browned and cooked through, 4-5 minutes per side. Turn off heat; transfer to a plate. \r\n\r\n\r\n4. \r\n\r\nOnce sweet potatoes have roasted 12 minutes, transfer baking sheet with zucchini to middle rack and continue roasting until both veggies are browned and softened, 12-15 minutes more. \r\n\r\n\r\n5. \r\n\r\nMeanwhile, melt 1 TBSP butter (2 TBSP for 4 servings) in pan used for pork over medium-high heat. Add apple and season with salt and pepper. Cook, scraping up any browned bits from bottom of pan, until apple is slightly softened, 2-3 minutes. Add garlic; cook until fragrant, 30 seconds. Add 1/z cup water (3/4 cup for 4), stock concentrate, and 11/2 tsp sugar (3 tsp for 4). Cook, stirring, until sauce has thickened and apple is very tender, 3-5 minutes. Season with salt and pepper. \r\n\r\n\r\n6. \r\n\r\nRemove pan with apple from heat; stir in 1 TBSP butter (2 TBSP for 4 servings) and a squeeze of lemon juice. Divide pork, zucchini, and sweet potatoes between plates. Top pork with glazed apple sauce. Top zucchini with a squeeze of lemon juice. ",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/h3ijwo1581013377.jpg",
      "strTags": null,
      "strYoutube": "",
      "strIngredient1": "Potatoes",
      "strIngredient2": "Apples",
      "strIngredient3": "Garlic",
      "strIngredient4": "Lemon",
      "strIngredient5": "Pork",
      "strIngredient6": "Zucchini",
      "strIngredient7": "Chicken Stock",
      "strIngredient8": "Vegetable Oil",
      "strIngredient9": "Sugar",
      "strIngredient10": "Butter",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "2",
      "strMeasure2": "1",
      "strMeasure3": "2 cloves",
      "strMeasure4": "1",
      "strMeasure5": "2",
      "strMeasure6": "1",
      "strMeasure7": "1",
      "strMeasure8": "1 tbsp",
      "strMeasure9": "1 1/2 tsp ",
      "strMeasure10": "2 tbsp",
      "strMeasure11": " ",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    }
  ]
};